# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MobileKit' do
  use_frameworks!
  pod 'Cache', '~> 4.1'
  pod 'SwiftyBeaver', '~> 1.4'
  pod 'ReachabilitySwift', '~> 4.3'
  pod 'FXKeychain', '~> 1.5'
  pod 'RxSwift', '~> 4.4'
  pod 'ReSwift', '~> 4.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Cache'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        else
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end
